name: core
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: ookami.kb <ookami.kb@gmail.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  built_value: ^6.7.1
  firebase: ^5.0.4
  json_annotation: ^3.0.0
  rxdart: ^0.22.2
  sealed_unions: ^3.0.2+2
  tuple: ^1.0.2

dev_dependencies:
  build_runner: ^1.5.0
  json_serializable: ^3.2.2
  pedantic: ^1.8.0
